*** Settings ***
Documentation    Локаторы экрана предоставления разрешения геолокации


*** Variables ***
${PERMISSION_FOREGROUND}    com.android.permissioncontroller:id/permission_allow_foreground_only_button
${PERMISSION_ALLOW}    com.android.permissioncontroller:id/permission_allow_button
${PERMISSION_ALLOW_OLD}    com.android.packageinstaller:id/permission_allow_button
${PERMISSION_DENY_BUTTON}    com.android.permissioncontroller:id/permission_deny_button
